language: rust
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
script:
  - cargo build --features "all"
  - cargo test --features "all"
- cargo doc --features "all"
