[package]

name = "pistoncore-glfw_window"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"]
tags = []
description = "A GLFW window back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/glfw_window.git"
homepage = "https://github.com/pistondevelopers/glfw_window"

[dependencies.pistoncore-window]

git = "https://github.com/PistonDevelopers/window"

[dependencies.pistoncore-input]

git = "https://github.com/PistonDevelopers/input"

[dependencies.shader_version]

git = "https://github.com/PistonDevelopers/shader_version"

[dependencies.glfw]

git = "https://github.com/bjz/glfw-rs"

[dependencies.gl]

git = "https://github.com/bjz/gl-rs"

[lib]

name = "glfw_window"
path = "src/lib.rs"

